name: weatherplay
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_bloc: ^7.0.0  
  flutter_riverpod: ^0.13.0
  equatable: ^2.0.0
  shared_preferences: ^2.0.7
  geolocator: ^7.4.0
  http: ^0.13.3
  intl: ^0.17.0
  responsive_grid: ^2.0.0
  rive: ^0.7.28
  animate_do: ^2.0.0
  sizer: ^2.0.13

  showcaseview: ^1.1.1
  device_preview: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  freezed: ^0.14.1+2
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^4.1.0
  lint: ^1.2.0

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "asset/image/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - asset/animation/starter.riv
    - asset/image/loader.png

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: asset/font/weathericons-regular.ttf
    - family: Porsche
      fonts:
        - asset: asset/font/Porsche.ttf
